package compiladorGo;

/* Generated By:JavaCC: Do not edit this line. GoGramaticaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GoGramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SOMA = 5;
  /** RegularExpression Id. */
  int SUBTRACAO = 6;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 7;
  /** RegularExpression Id. */
  int DIVISAO = 8;
  /** RegularExpression Id. */
  int IGUAL = 9;
  /** RegularExpression Id. */
  int COMPARACAO = 10;
  /** RegularExpression Id. */
  int DIFERENTE = 11;
  /** RegularExpression Id. */
  int MAIOR = 12;
  /** RegularExpression Id. */
  int MENOR = 13;
  /** RegularExpression Id. */
  int MAIORIGUAL = 14;
  /** RegularExpression Id. */
  int MENORIGUAL = 15;
  /** RegularExpression Id. */
  int AND = 16;
  /** RegularExpression Id. */
  int OR = 17;
  /** RegularExpression Id. */
  int NOT = 18;
  /** RegularExpression Id. */
  int ANDPER = 19;
  /** RegularExpression Id. */
  int DOISPONTOS = 20;
  /** RegularExpression Id. */
  int PACKAGE = 21;
  /** RegularExpression Id. */
  int IMPORT = 22;
  /** RegularExpression Id. */
  int FUNC = 23;
  /** RegularExpression Id. */
  int VAR = 24;
  /** RegularExpression Id. */
  int IF = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int FOR = 27;
  /** RegularExpression Id. */
  int RANGE = 28;
  /** RegularExpression Id. */
  int TRUE = 29;
  /** RegularExpression Id. */
  int FALSE = 30;
  /** RegularExpression Id. */
  int RETURN = 31;
  /** RegularExpression Id. */
  int PRINT = 32;
  /** RegularExpression Id. */
  int ENTRADA = 33;
  /** RegularExpression Id. */
  int TIPO = 34;
  /** RegularExpression Id. */
  int INTEIRO = 35;
  /** RegularExpression Id. */
  int REAL = 36;
  /** RegularExpression Id. */
  int STRING = 37;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"&\"",
    "\":\"",
    "\"package\"",
    "\"import\"",
    "\"func\"",
    "\"var\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"range\"",
    "\"true\"",
    "\"false\"",
    "\"return\"",
    "\"fmt.Println\"",
    "\"fmt.Scanln\"",
    "<TIPO>",
    "<INTEIRO>",
    "<REAL>",
    "<STRING>",
    "<IDENTIFICADOR>",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"_\"",
  };

}
